<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<div>
        <div class="toolbar-bottom">
            <div class="toolbar bottom">
                <?php echo $block->getPagerHtml(); ?>
            </div>
        </div>
    <form action='<?php echo $block->saveCategoryUrl(); ?>'
          id="add_category_form" method="post">
        <p class="mp_seller_comments">
            <label for="category"> <?php echo __('Name:'); ?>  </label><em style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em>
            <input type="text" name="name" data-validate="{required:true}"/>
        </p>
        <p class="mp_seller_comments">
            <label for="feedback"> <?php echo __('Description:'); ?>  </label><em style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em>
            <textarea id="feedback" rows="9" cols="49"
                      name="description" class="input-text"
                      data-validate="{required:true}"></textarea>
        </p>
	<input type="hidden" name="parent_category" id="parent_category" value="" />
        <button type="submit" class="button"
                title="<?php echo __('Submit Category') ?>"
                name="submit_category">
            <span><span><?php echo __('Submit') ?></span></span>
        </button>
    </form>
</div>