<fieldset class="fieldset">
<div class="product-url">
                <a href="<?php echo $block->getUrl('marketplace/category/add') ?>"
                    class="action submit primary"><?php echo __('Add New Category'); ?></a>
 </div>
</fieldset>

<div class="toolbar top">
         <?php echo $block->getPagerHtml(); ?>
      </div>

<table class="manage-product-table">
 <tr class="header" style="background: #ddd;">
<th><?php echo __('Category Name')?></th>
<th><?php echo __('Category Description')?></th>
<th><?php echo __('Parent Category')?></th>
<th><?php echo __('Status')?></th>
<th><?php echo __('Action')?></th>
</tr>
<?php foreach($block->getCategories() as $category): ?>
<tr>
<td> <?= $category->getData('category_name') ?> </td>
<td> <?= $category->getData('category_description') ?> </td>
<td> <?= $block->getCategoryNameById($category->getData('parent_category_id')) ?> </td>

<td> <?php if($category->getData('status') == 1){
echo __("Approved") ;
}elseif($category->getData('status') == 0){
echo __("Disapproved");
}else{
echo __("Modified");
} ?> </td>
<td> <a href="<?= $block->getUrl('*/*/edit', ['id' => $category->getData('id')]) ?>"> Edit </a> </td>
</tr>
<?php endforeach; ?>
</table>

<div class="toolbar-bottom">
                <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
</div>